### PR TITLE
Update to use latest protobuf

### PR DESCRIPTION
**Pull request by michaeldelago**
This is based on the work in #434 by @Partmedia

This PR adds the missing `include` statements as well as a few tweaks to the Makefile to get everything working.

Changes to the Makefile

- use `-std=c++17` instead of `-std=c++14`. It wasn't working on my machine with 14
- use `pkg-config` to setup linking for absl and protobuf
  - absl apparently only supports Bazel and CMake. There's a BUILD file in there but I have no idea how to use bazel and the README.md states to use `make`

### CODE REVIEW

**Comment by Partmedia** [comment]
Thanks for improving on this. I have to remember to go back and fix the workflows on my PR :')

I might offer that the reason only c++17 works is that you may be linking to a system abseil library compiled with C++17 flags (the linked library is not cross-C++ runtime ABI compatible). That's why I also needed C++17 on my machine to get this to compile, but I opted not to include that in the PR.

**Comment by Slids** [comment]
Fails CI (which should at least pass ccl and sbcl

**Comment by michaeldelago** [comment]
CI fixed (maybe). They weren't installing absl in the setup steps.

> I might offer that the reason only c++17 works is that you may be linking to a system abseil library compiled with C++17 flags (the linked library is not cross-C++ runtime ABI compatible).

That makes sense. I'm using the current version of protobuf that's in the Arch Linux package repository, so I didn't compile it myself.

**Comment by Slids** [comment]
CCL and SBCL are not yet passing CI

**Comment by Slids** [comment]
So, the issue is the ubuntu repository used in ubuntu-latest doesn't have absl_absl_log in libabsl-dev.

**Comment by Slids** [comment]
https://abseil.io/docs/cpp/tools/cmake-installs 
Will tell you how to build and install.

Installing is slow, not quite sure what to do about that, 
but I think it's the best way forward?

**Comment by michaeldelago** [comment]
work picked up - unfortunately too distracted to give this as much time as I wanted

nicely, this is superseded by #438

**Pull request closed without merging**
