### PR TITLE
Ensure timestamps print either 0, 3, 6, or 9 fractional digits

### PR DESCRIPTION
**Pull request by bkuehnert**
This is required by protobuf spec

### CODE REVIEW

**Review by cgay — APPROVED** [review]

**Comment by cgay** [comment]
```
 Dynamic variable name +RFC-3339-PREFIX+ should begin and end with '*'. (DYNAMIC-NAME)
	//depot/google3/third_party/lisp/cl_protobufs/json.lisp:650
  No docstring for special variable +RFC-3339-PREFIX+. (MISSING-DOCUMENTATION)
	//depot/google3/third_party/lisp/cl_protobufs/json.lisp:650
  Dynamic variable name +RFC-3339-SUFFIX+ should begin and end with '*'. (DYNAMIC-NAME)
	//depot/google3/third_party/lisp/cl_protobufs/json.lisp:652
  No docstring for special variable +RFC-3339-SUFFIX+. (MISSING-DOCUMENTATION)
	//depot/google3/third_party/lisp/cl_protobufs/json.lisp:652
  Dynamic variable name +RFC-3339-0-FRAC+ should begin and end with '*'. (DYNAMIC-NAME)
	//depot/google3/third_party/lisp/cl_protobufs/json.lisp:653
  No docstring for special variable +RFC-3339-0-FRAC+. (MISSING-DOCUMENTATION)
	//depot/google3/third_party/lisp/cl_protobufs/json.lisp:653
  Dynamic variable name +RFC-3339-3-FRAC+ should begin and end with '*'. (DYNAMIC-NAME)
	//depot/google3/third_party/lisp/cl_protobufs/json.lisp:654
  No docstring for special variable +RFC-3339-3-FRAC+. (MISSING-DOCUMENTATION)
	//depot/google3/third_party/lisp/cl_protobufs/json.lisp:654
  Dynamic variable name +RFC-3339-6-FRAC+ should begin and end with '*'. (DYNAMIC-NAME)
	//depot/google3/third_party/lisp/cl_protobufs/json.lisp:655
  No docstring for special variable +RFC-3339-6-FRAC+. (MISSING-DOCUMENTATION)
	//depot/google3/third_party/lisp/cl_protobufs/json.lisp:655
  Dynamic variable name +RFC-3339-9-FRAC+ should begin and end with '*'. (DYNAMIC-NAME)
	//depot/google3/third_party/lisp/cl_protobufs/json.lisp:656
  No docstring for special variable +RFC-3339-9-FRAC+. (MISSING-DOCUMENTATION)
	//depot/google3/third_party/lisp/cl_protobufs/json.lisp:656
```

**Comment by Slids** [comment]
ERROR: FAIL: SIMPLE-WARNING 'undefined variable: CL-PROTOBUFS.JSON::*RFC-3339-0-FRAC*'

; file: third_party/lisp/cl_protobufs/json.lisp
; in: DEFUN CL-PROTOBUFS.JSON::PRINT-SPECIAL-JSON
;     (COND ((= CL-PROTOBUFS.JSON::NSEC 0) CL-PROTOBUFS.JSON::*RFC-3339-0-FRAC*)
;           ((= (MOD CL-PROTOBUFS.JSON::NSEC 1000000) 0)
;            CL-PROTOBUFS.JSON::*RFC-3339-3-FRAC*)
;           ((= (MOD CL-PROTOBUFS.JSON::NSEC 1000) 0)
;            CL-PROTOBUFS.JSON::*RFC-3339-6-FRAC*)
;           (T CL-PROTOBUFS.JSON::*RFC-3339-9-FRAC*))
; ==>
;   (IF (= CL-PROTOBUFS.JSON::NSEC 0)
;       CL-PROTOBUFS.JSON::*RFC-3339-0-FRAC*
;       (IF (= (MOD CL-PROTOBUFS.JSON::NSEC 1000000) 0)
;           CL-PROTOBUFS.JSON::*RFC-3339-3-FRAC*
;           (IF (= (MOD CL-PROTOBUFS.JSON::NSEC 1000) 0)
;               CL-PROTOBUFS.JSON::*RFC-3339-6-FRAC*
;               (THE T CL-PROTOBUFS.JSON::*RFC-3339-9-FRAC*))))
; 
; caught WARNING:
;   undefined variable: CL-PROTOBUFS.JSON::*RFC-3339-0-FRAC*
ERROR: FAIL: SIMPLE-WARNING 'undefined variable: CL-PROTOBUFS.JSON::*RFC-3339-3-FRAC*'

**Comment by cgay** [comment]
I think the `defparameter` forms need to precede their uses in the source.

**Comment by Slids** [comment]
No, still failing, wondering why though...

**Comment by bkuehnert** [comment]
It probably doesn't like the fact that I have globals defined in a let binding

**Comment by Slids** [comment]
It's probably not great style, but it makes me wonder why asdf works but we fail internally

**Comment by bkuehnert** [comment]
I'll fix it tomorrow. It also feels bad to define a global that gets used once and is then immediately thrown away...

**Comment by cgay** [comment]
I would just copy the time format in 4 places. No big deal. Align them vertically so you can see they're all the same.

(It would be somewhat prettier if local-time has a `parse-time-format` function and you could specify the formats as strings, as well as getting load-time error detection.)

**Comment by cgay** [comment]
Compile time if you `#.(parse-time-format ...)`

**Pull request merged**
